name: Docker Check

on:
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: web-app/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
